name: Continuous Integration

on: [push, pull_request] 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
    - name: Restore Packages
      run: |
        cd src/
        nuget restore
      
    - name: Build Solution
      run: |
        cd src/
        msbuild.exe

    - name: Run Unit Tests
      run: |
        cd src/SearchAlgorithms.UnitTests/bin/Debug/
        vstest.console.exe SearchAlgorithms.UnitTests.dll
        